specVersion: 0.2.0
name: subql-rococo
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xaaf2cd1b74b5f726895921259421b534124726263982522174147046b8827897'
  endpoint: wss://rococo-rpc.polkadot.io
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
