specVersion: 0.2.0
name: subql-dusty
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xbadd1afcab647246f96c072799f519f451cf91690c02051856a6b1d9b194a360'
  endpoint: wss://rpc.dusty.plasmnet.io
dataSources:
  - kind: substrate/Runtime
    startBlock: 1409042
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
